Repository ESTSOFT-iOS-01/RunLog, pull requests merged in 2025-03, with the labels that each got.

#5 Revert "[#1] 테스트용 커밋1"
  README.md
Labels: ✅ test

#7 [#6] 커밋 테스트
  README.md
Labels: ✅ test

#10 [feature] Appconfig, DayLog, Section Entity 추가
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Domain/Entity/AppConfig.swift
  RunLog/RunLog/Sources/Domain/Entity/DayLog.swift
  RunLog/RunLog/Sources/Domain/Entity/Section.swift
Labels: ✨ feature

#11 [chore] 디자인 시스템 세팅
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Resources/DesignSystem/ColorSystem.swift
  RunLog/RunLog/Resources/DesignSystem/FontSystem.swift
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Resources/DesignSystem/TextSystem.swift
  RunLog/RunLog/Resources/Fonts/Pretendard-Black.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-Bold.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-ExtraBold.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-ExtraLight.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-Light.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-Medium.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-Regular.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-SemiBold.otf
  RunLog/RunLog/Resources/Fonts/Pretendard-Thin.otf
  RunLog/RunLog/Sources/Data/DTO/.gitkeep
  RunLog/RunLog/Sources/Presentation/Common/View/ViewController.swift
  RunLog/RunLog/Sources/Util/Extension/UIColor+Extension.swift
Labels: ⚙️ chore

#15 [feature] 네비게이션 바 스타일 설정
  RunLog/RunLog/Sources/Util/Extension/UIColor+.swift
  RunLog/RunLog/Sources/Util/Extension/UINavigationController+.swift
Labels: ✨ feature

#16 [feature] 버튼 디자인 시스템 개발
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Resources/DesignSystem/ButtonSystem.swift
  RunLog/RunLog/Sources/Presentation/Common/View/ViewController.swift
  RunLog/RunLog/Sources/Util/Extension/UIColor+.swift
  RunLog/RunLog/Sources/Util/Extension/UIView+.swift
Labels: ✨ feature

#21 [Feature] 마이페이지 메인 화면 개발 완료
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Resources/DesignSystem/ColorSystem.swift
  RunLog/RunLog/Resources/DesignSystem/FontSystem.swift
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Resources/DesignSystem/TextSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/.gitkeep
  RunLog/RunLog/Sources/Presentation/Setting/View/MypageProfileView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/ProfileCardView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/SettingMenuCell.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeCalUnitViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeNicknameViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/.gitkeep
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/MyPage.swift
  RunLog/RunLog/Sources/Util/Extension/.gitkeep
  RunLog/RunLog/Sources/Util/Extension/Double+.swift
  RunLog/RunLog/Sources/Util/Extension/Int+.swift
  RunLog/RunLog/Sources/Util/Extension/String+.swift
  RunLog/RunLog/Sources/Util/Extension/UIColor+.swift
Labels: ✨ feature

#23 [feature] Log 뷰 구현
  RunLog/RunLog/Resources/Assets.xcassets/walk.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/walk.imageset/walk.png
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/Presentation/Log/Component/UnderlineSegmentedControl.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
Labels: ✨ feature

#25 [feature] 상세기록 뷰 개발 1차
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Resources/DesignSystem/LabelSystem.swift
  RunLog/RunLog/Sources/Presentation/Log/View/.gitkeep
  RunLog/RunLog/Sources/Presentation/Log/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/MypageProfileView.swift
Labels: ✨ feature

#27 [feature] 텍스트필트 컴포넌트 개발
  RunLog/RunLog/Resources/DesignSystem/TextFieldSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Presentation/Common/View/ViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
Labels: ✨ feature

#24 [feature] Run 뷰 구현 완료
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RunLog/RunLog.xcodeproj/xcshareddata/xcschemes/RunLog.xcscheme
  RunLog/RunLog/Resources/DesignSystem/ButtonSystem.swift
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Resources/DesignSystem/TextSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Presentation/Common/View/MainTabBarController.swift
  RunLog/RunLog/Sources/Presentation/Common/View/ViewController.swift
  RunLog/RunLog/Sources/Presentation/Common/ViewModel/LocationManager.swift
  RunLog/RunLog/Sources/Presentation/Run/View/.gitkeep
  RunLog/RunLog/Sources/Presentation/Run/View/CardElementView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/MapBlurView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Util/Extension/Double+.swift
  RunLog/RunLog/Sources/Util/Extension/UIViewController+.swift
Labels: ✨ feature

#34 [feature] 테이블뷰 완료
  RunLog/RunLog/Sources/Presentation/DetailLog/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/RecordDetailView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/RecordDetailViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/DetailLogViewModel.swift
Labels: ✨ feature

#36 [feature] 설정 세부 페이지 mvvm + Combine 사용하여 기능 개발
  RunLog/RunLog/Resources/DesignSystem/TextFieldSystem.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/CalUnitView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/ChangeNicknameView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/MypageProfileView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/ProfileCardView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/SettingMenuCell.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeCalUnitViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeNicknameViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/CalUnitViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/ChangeNicknameViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/MyPage.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/MyPageViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/UINavigationController+.swift
  RunLog/RunLog/Sources/Util/Extension/UIViewController+.swift
Labels: ✨ feature

#38 [feature] 네트워크 관련 기본 세팅 완료
  RunLog/RunLog/Sources/Data/Network/Error.swift
  RunLog/RunLog/Sources/Data/Network/NetworkProtocol.swift
Labels: ✨ feature

#40 [feature] LogView 기능 구현(더미데이터 연결)
  RunLog/RunLog/Resources/Assets.xcassets/noneBeat.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/noneBeat.imageset/noneBeat.png
  RunLog/RunLog/Resources/Assets.xcassets/oneBeat.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/oneBeat.imageset/oneBeat.png
  RunLog/RunLog/Resources/Assets.xcassets/threeBeats.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/threeBeats.imageset/threeBeats.png
  RunLog/RunLog/Resources/Assets.xcassets/twoBeats.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/twoBeats.imageset/twoBeats.png
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/Presentation/Common/View/MainTabBarController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/Model/CalendarDay.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
Labels: ✨ feature

#42 [feature] 로그 세부사항 변경 페이지 UI 및 기능
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/Presentation/Log/Component/RadioButtonCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/EditLog/EditLogInfoView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/EditLog/EditLogInfoViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/EditLogInfoViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/MypageProfileView.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
Labels: ✨ feature

#45 [feature] DTO 정의 및 Model Mapping
  RunLog/RunLog/Sources/Data/DTO/DTOs.xcdatamodeld/DTOs.xcdatamodel/contents
  RunLog/RunLog/Sources/Data/DTO/DataMapper.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Repository/DayLogRepository.swift
Labels: ✨ feature

#43 [feature] 뷰모델을 통한 뷰 업데이트 및 맵뷰 적용
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Info.plist
  RunLog/RunLog/Sources/Presentation/Common/ViewModel/.gitkeep
  RunLog/RunLog/Sources/Presentation/Common/ViewModel/LocationManager.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardElementView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/.gitkeep
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunHomeViewModel.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunningViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/SettingMenuCell.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
  RunLog/RunLog/Sources/Util/Extension/MKMapView+.swift
Labels: ✨ feature

#44 [feature] 바텀시트 개발완료
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/MovingTrackSheetView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/MovingTrackSheetViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailViewCell.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/DetailLogViewModel.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/MovingTrackSheet.swift
Labels: ✨ feature

#53 [feature] AppConfig Repo, RepoImpl 작성
  RunLog/RpTest/RpTest.swift
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog.xcodeproj/xcshareddata/xcschemes/RunLog.xcscheme
  RunLog/RunLog/Sources/Data/Impl/.gitkeep
  RunLog/RunLog/Sources/Data/Impl/AppConfigRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Entity/.gitkeep
  RunLog/RunLog/Sources/Domain/Repository/.gitkeep
  RunLog/RunLog/Sources/Domain/Repository/AppConfigRepository.swift
Labels: ✨ feature

#52 [feature] ui메뉴 뷰 개발 완료
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/DetailLogViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/UINavigationController+.swift
Labels: ✨ feature

#56 [feature] AppConfig Usecase 개발 완료
  RunLog/RpTest/DoubleTest.swift
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Resources/Assets.xcassets/Church.imageset/Church.png
  RunLog/RunLog/Resources/Assets.xcassets/Church.imageset/Church@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Church.imageset/Church@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Church.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Earth.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Earth.imageset/Earth.png
  RunLog/RunLog/Resources/Assets.xcassets/Earth.imageset/Earth@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Earth.imageset/Earth@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Flag.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Flag.imageset/Flag.png
  RunLog/RunLog/Resources/Assets.xcassets/Flag.imageset/Flag@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Flag.imageset/Flag@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Korea.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Korea.imageset/Korea.png
  RunLog/RunLog/Resources/Assets.xcassets/Korea.imageset/Korea@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Korea.imageset/Korea@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Mandarin.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Mandarin.imageset/Mandarin.png
  RunLog/RunLog/Resources/Assets.xcassets/Mandarin.imageset/Mandarin@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Mandarin.imageset/Mandarin@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Medal.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Medal.imageset/Medal.png
  RunLog/RunLog/Resources/Assets.xcassets/Medal.imageset/Medal@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Medal.imageset/Medal@3x.png
  RunLog/RunLog/Resources/Assets.xcassets/Rocket.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/Rocket.imageset/Rocket.png
  RunLog/RunLog/Resources/Assets.xcassets/Rocket.imageset/Rocket@2x.png
  RunLog/RunLog/Resources/Assets.xcassets/Rocket.imageset/Rocket@3x.png
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Entity/Road.swift
  RunLog/RunLog/Sources/Domain/UseCase/.gitkeep
  RunLog/RunLog/Sources/Domain/UseCase/AppConfigUsecase.swift
  RunLog/RunLog/Sources/Domain/UseCase/AppConfigUsecaseImpl.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailView.swift
  RunLog/RunLog/Sources/Util/Extension/Double+.swift
Labels: ✨ feature

#59 [feature] DaylogRepository&CoreDataContainer 작성
  RunLog/RpTest/RpTest.swift
  RunLog/RpTest/TestCoreDataContainer.swift
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Data/CoreDataContainer.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Entity/AppConfig.swift
  RunLog/RunLog/Sources/Domain/Entity/DayLog.swift
  RunLog/RunLog/Sources/Domain/Entity/Section.swift
  RunLog/RunLog/Sources/Domain/Repository/DayLogRepository.swift
Labels: ✨ feature

#62 [feature] DayLogUseCase Protocol & 구현체 작성완료
  RunLog/RpTest/DayLogUseCaseTest.swift
  RunLog/RunLog/Sources/Data/DTO/DTOs.xcdatamodeld/DTOs.xcdatamodel/contents
  RunLog/RunLog/Sources/Data/DTO/DataMapper.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Entity/DayLog.swift
  RunLog/RunLog/Sources/Domain/UseCase/DayLogUseCase.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/AppConfigUsecaseImpl.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
Labels: ✨ feature

#63 [feature]데이터 연결 완료
  RunLog/RunLog/Sources/Presentation/Common/ViewModel/LocationManager.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/DisplayDayLog.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/RecordDetail.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/MovingTrackSheetView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailViewCell.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/MovingTrackSheetViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
  RunLog/RunLog/Sources/Util/Extension/DayLog+.swift
  RunLog/RunLog/Sources/Util/Extension/Int+.swift
  RunLog/RunLog/Sources/Util/Extension/TimeInterval+.swift
Labels: ✨ feature

#66 [feature] DIContainer 구현 및 LogView 데이터 연결
  RunLog/RpTest/DayLogUseCaseTest.swift
  RunLog/RunLog/Sources/App/AppDelegate.swift
  RunLog/RunLog/Sources/App/DIContainer.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Domain/UseCase/DayLogUseCase.swift
  RunLog/RunLog/Sources/Domain/UseCase/MediaUseCase.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/MediaUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
Labels: ✨ feature

#68 [feature] 운동데이터 연결, 날씨, 대기질 연결
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Info.plist
  RunLog/RunLog/Sources/Data/DistanceManager.swift
  RunLog/RunLog/Sources/Data/LocationManager.swift
  RunLog/RunLog/Sources/Data/Network/API.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeatherEndpoint.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeatherService.swift
  RunLog/RunLog/Sources/Data/PedometerManager.swift
  RunLog/RunLog/Sources/Presentation/Common/Dummy/Dummy.swift
  RunLog/RunLog/Sources/Presentation/Common/ViewModel/LocationManager.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardElementView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/MapBlurView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunHomeViewModel.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunningViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/Bundle+.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
Labels: ✨ feature

#70 [feature] LogView에서 상세 뷰 연결 및 중복 생성 방지
  RunLog/RpTest/DayLogUseCaseTest.swift
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/DisplayDayLog.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/DetailLogViewModel.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/Date+.swift
  RunLog/RunLog/Sources/Util/Extension/UINavigationController+.swift
Labels: ✨ feature

#78 [bugfix] date 버그 수정
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
Labels: 🐞 bug

#75 [feature] DetailLogView 데이터 연결(UseCase 적용)
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Data/Impl/AppConfigRepositoryImpl.swift
  RunLog/RunLog/Sources/Domain/Repository/DayLogRepository.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/DetailLogViewModel.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogViewController.swift
Labels: ✨ feature

#76 [feature] 유스케이스 적용 및 Running Data Provider 추가
  RunLog/RunLog/Sources/Data/DistanceManager.swift
  RunLog/RunLog/Sources/Data/DrawingManager.swift
  RunLog/RunLog/Sources/Data/LocationManager.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeather/OpenWeatherEndpoint.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeather/OpenWeatherModel.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeather/OpenWeatherService.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeatherService.swift
  RunLog/RunLog/Sources/Data/PedometerManager.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/DayLogUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/Common/Dummy/Dummy.swift
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunHomeViewModel.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunningViewModel.swift
  RunLog/RunLog/Sources/Util/Constant/Constants.swift
  RunLog/RunLog/Sources/Util/Extension/CLPlacemark+.swift
Labels: ✨ feature

#85 [feature] Road View 데이터 연결 및 카메라 초기 위치, 줌 세팅
  RunLog/RunLog/Sources/App/AppDelegate.swift
  RunLog/RunLog/Sources/Domain/UseCase/AppConfigUseCase.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/AppConfigUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunHomeViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/CalUnitViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/ChangeNicknameViewModel.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/MyPageViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/MKMapView+.swift
Labels: ✨ feature

#80 [feature] TabBar & Navigation Bar 수정
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/Presentation/Common/View/MainTabBarController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
Labels: ✨ feature

#83 [feature] 랜덤 멘트 기능 추가 및 appconfig 연결(닉네임, distanceUnit)
  RunLog/RunLog/Resources/Assets.xcassets/walk.imageset/walk.png
  RunLog/RunLog/Resources/Assets.xcassets/walkDog.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/walkDog.imageset/walkDog.png
  RunLog/RunLog/Resources/Assets.xcassets/walkGirl.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/walkGirl.imageset/walkGirl.png
  RunLog/RunLog/Resources/Assets.xcassets/walkMan.imageset/Contents.json
  RunLog/RunLog/Resources/Assets.xcassets/walkMan.imageset/walkMan.png
  RunLog/RunLog/Resources/DesignSystem/IconSystem.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/LogViewModel.swift
  RunLog/RunLog/Sources/Util/Constant/Constants.swift
Labels: ✨ feature

#92 [feature] 다이나믹 사이즈 코드 추가 및 적용
  RunLog/RunLog/Resources/DesignSystem/ButtonSystem.swift
  RunLog/RunLog/Resources/DesignSystem/FontSystem.swift
  RunLog/RunLog/Resources/DesignSystem/LabelSystem.swift
  RunLog/RunLog/Resources/DesignSystem/TextFieldSystem.swift
  RunLog/RunLog/Sources/App/SceneDelegate.swift
  RunLog/RunLog/Sources/Presentation/Run/View/CardView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/MapBlurView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunningViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/RunHomeViewModel.swift
  RunLog/RunLog/Sources/Util/Constant/Constants.swift
  RunLog/RunLog/Sources/Util/Constant/DynamicSize.swift
  RunLog/RunLog/Sources/Util/Extension/CLPlacemark+.swift
Labels: ✨ feature

#95 [feature] MediaUsecase 경로 사진 저장 프로토콜 및 기능 개발
  RunLog/RpTest/MediaUseCaseTests.swift
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Domain/UseCase/MediaUseCase.swift
  RunLog/RunLog/Sources/Domain/UseCaseImpl/MediaUseCaseImpl.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
  RunLog/RunLog/Sources/Presentation/Run/ViewModel/Coordinator/.gitkeep
Labels: ✨ feature

#101 [feature] 미디어 유스케이스 연결
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
Labels: ✨ feature

#107 [feature] LogView 다이나믹 사이즈 적용
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewCell.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Calendar/CalendarViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/LogView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/Timeline/TimelineViewCell.swift
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
Labels: ✨ feature

#108 [feature] 위치, 날씨 표기 수정 및 셀 터치시 맵뷰 줌 기능 추가
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/DisplayDayLog.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Util/Extension/Int+.swift
Labels: ✨ feature

#110 [feature] 기록 수정 페이지 뷰모델 적용되는 것 확인
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/View/EditLog/EditLogInfoViewController.swift
  RunLog/RunLog/Sources/Presentation/Log/ViewModel/EditLogInfoViewModel.swift
  RunLog/RunLog/Sources/Util/Constant/Constants.swift
Labels: ✨ feature, 🔨 refactor

#103 [feature] 제작한 페이지에 대한 다이나믹 패딩 적용
  RunLog/RunLog/Sources/Data/Impl/DayLogRepositoryImpl.swift
  RunLog/RunLog/Sources/Presentation/Log/View/EditLog/EditLogInfoView.swift
  RunLog/RunLog/Sources/Presentation/Log/View/EditLog/EditLogInfoViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/CalUnitView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/ChangeNicknameView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/MypageProfileView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/ProfileCardView.swift
  RunLog/RunLog/Sources/Presentation/Setting/View/SettingMenuCell.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeCalUnitViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/ChangeNicknameViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
Labels: 🐞 bug, ✨ feature, 🔨 refactor

#113 [bugfix] blurView 레이아웃 충돌 해결
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog/Sources/Presentation/Run/View/MapBlurView.swift
  RunLog/RunLog/Sources/Presentation/Run/View/RunHomeViewController.swift
Labels: 🐞 bug

#117 [#refactor] 더미 Set 제거
  RunLog/RunLog/Sources/Data/PedometerManager.swift
  RunLog/RunLog/Sources/Presentation/Run/RunningDataProvider.swift
Labels: 🔨 refactor

#115 [feature] 다이나믹패딩 완료
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/MovingTrackSheetView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/RecordDetailViewCell.swift
Labels: ✨ feature

#109 [feature] 로딩인디케이터 + 네트워크 에러 핸들링 및 상세 오류 메세지 출력
  RunLog/RunLog.xcodeproj/project.pbxproj
  RunLog/RunLog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RunLog/RunLog/Sources/Data/Network/Error.swift
  RunLog/RunLog/Sources/Data/Network/NetworkProtocol.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeather/OpenWeatherEndpoint.swift
  RunLog/RunLog/Sources/Data/Network/OpenWeather/OpenWeatherService.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewController/MyPageViewController.swift
  RunLog/RunLog/Sources/Presentation/Setting/ViewModel/MyPageViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/Bundle+.swift
  RunLog/RunLog/Sources/Util/Extension/UIViewController+.swift
Labels: ✨ feature

#121 [Bugfix] 셀탭 호출 및 정렬 수정
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/DisplayDayLog.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/Model/RecordDetail.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogView.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/DetailLogViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/View/MovingTrackSheetViewController.swift
  RunLog/RunLog/Sources/Presentation/DetailLog/ViewModel/DetailLogViewModel.swift
  RunLog/RunLog/Sources/Util/Extension/UITapGestureRecognizer+.swift
Labels: 🐞 bug

#123 [docs] 리드미 수정
  README.md
Labels: 📃 docs
